### PR TITLE
[Feature] Delete key to remove log files

### PR DESCRIPTION
**Pull request by Hrishi1999**
Pressing delete key on the keyboard will now remove the selected log file (https://github.com/sugarlabs/log-activity/issues/17)

### CODE REVIEW

**Comment by nswarup14** [comment]
I think the `delete-key-event` can be isolated. If a user clicks on any other button after selecting a logfile from the `treeview`, the `treeview-delete` is emitted which causes the log file to get deleted.

Perhaps the following line can be added inside the `_treeview_key_press_cb` to isolate the event
```
keyname = Gdk.keyval_name(event.keyval).lower()
if keyname == 'delete':
      self.emit('treeview-delete')
```

**Comment by quozl** [comment]
Nicely spotted.

**Comment by Hrishi1999** [comment]
Thanks for the suggestion. I did implement a similar method, but I pushed this changes from a older VM. I will fix it. Thanks for spotting it out

**Comment by quozl** [comment]
Thanks.  Regarding OLPC XO, we don't have a Delete key.  :grin:

I'm surprised you don't use an accelerator on the _Delete Log File_ button.  It should be much less change, and the tooltip shows what the accelerator is.  This is tested;

```diff
--- a/logviewer.py
+++ b/logviewer.py
@@ -534,7 +534,7 @@ class LogActivity(activity.Activity):
         collector_btn.show()
         activity_toolbar.insert(collector_btn, -1)
 
-        self._delete_btn = ToolButton('list-remove')
+        self._delete_btn = ToolButton('list-remove', accelerator='<ctrl>d')
         self._delete_btn.set_tooltip(_('Delete Log File'))
         self._delete_btn.connect('clicked', self._delete_log_cb)
         self._toolbar.insert(self._delete_btn, -1)
```

**Comment by nswarup14** [comment]
Yes,
I agree that adding an accelerator would be a easier thing to implement, with fewer changes.
Thanks.

**Comment by Hrishi1999** [comment]
It didn't strike in my mind to use accelerators (not familiar using it). I will do the required changes. Thanks for your input :)

**Pull request merged**
